Fix compilation on JDK >= 9
In java9 interface Action get default method `accept` which conflicts with some methods in the codebase:
```
error: method accept in interface Action cannot be applied to given types;
        accept();
  required: Object
  found: no arguments
  reason: actual and formal argument lists differ in length
```
See https://docs.oracle.com/javase/9/docs/api/javax/swing/Action.html#accept-java.lang.Object-.